### ISSUE TITLE
Broken handling of images, other void nodes

### ISSUE THREAD

**Issue by wooorm** [ben-eb/remark-word-wrap#1]
`remark-word-wrap` reaches an infite loop when nodes without `children` and without `value` are found (other examples can be found by searching `<: Node` on [MDAST](https://github.com/wooorm/mdast)s repo).

**Comment by ben-eb** [comment]
Fixed by https://github.com/ben-eb/remark-word-wrap/commit/0c53e60290a7bfbdfb04bca19f75ab66dbe85814.
