### ISSUE TITLE
Broken handling of first child of links when it doesn’t have a value

### ISSUE THREAD

**Issue by wooorm** [ben-eb/remark-word-wrap#2]
[L33](https://github.com/ben-eb/remark-word-wrap/blob/b0af9c91f5c2e9dfe5061bd3c76c3e461d1369ea/src/index.js#L33).

Can occur with badges (e.g., a travis image inside a link), or with emphasis, but also for empty links (which are weird but perfectly valid).

**Comment by ben-eb** [comment]
Fixed by https://github.com/ben-eb/remark-word-wrap/commit/0c53e60290a7bfbdfb04bca19f75ab66dbe85814.
