### ISSUE TITLE
package dependencies are incomplete/undocumented

### ISSUE THREAD

**Issue by jong** [ben-eb/remark-word-wrap#45]
Caveat: I am a total node.js newb.

These are some versions of my environment:
```
/remark-word-wrap # node --version && npm --version
v10.15.0
6.5.0
```

I started looking into fixing #4, but ran into some issues. The first thing I was trying to do was run tests, but they would not run. I installed `remark-work-wrap` locally using: `npm install --dev .` but was getting this error when running tests:

```
/remark-word-wrap # npm test

> remark-word-wrap@2.0.2 pretest /remark-word-wrap
> eslint src


> remark-word-wrap@2.0.2 test /remark-word-wrap
> npm run markdown && nyc --reporter=text ava src/__tests__


> remark-word-wrap@2.0.2 markdown /remark-word-wrap
> remark *.md --quiet

README.md
  1:1  error  Error: Invalid example `/remark-word-wrap/example.js`. Ensure example is a valid JavaScript file:

Cannot find module './dist/index.js'
```

I looked at `example.js` and changed it to use `src` instead. I got further, but still ran into an error:

```
/remark-word-wrap # npm test

> remark-word-wrap@2.0.2 pretest /remark-word-wrap
> eslint src


> remark-word-wrap@2.0.2 test /remark-word-wrap
> npm run markdown && nyc --reporter=text ava src/__tests__


> remark-word-wrap@2.0.2 markdown /remark-word-wrap
> remark *.md --quiet

README.md
  1:1  error  /remark-word-wrap/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import is from 'unist-util-is';
                                                                     ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

✖ 1 error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remark-word-wrap@2.0.2 markdown: `remark *.md --quiet`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remark-word-wrap@2.0.2 markdown script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-18T17_27_39_686Z-debug.log
npm ERR! Test failed.  See above for more details.
```

I looked into the import issue and got lost in the world of node.js imports, ES6, babel and other things. I have a recent version of node, and I know running `remark` itself works fine otherwise, so as a hailmary I installed everything else I was using with remark, locally:

```
npm install remark-cli@6.0.1 \
    remark-lint@6.0.4 \
    remark-toc@5.1.1 \
    remark-heading-gap@3.1.0;
```

I was then able to successfully run tests. I would fix this but I don't know enough about the ecosystem to know where to start!

**Comment by wooorm** [comment]
This project hasn’t received updates in a while, and never properly worked.
Maybe updating the dependencies and fixing all the scripts first helps?
I did update [remark-autolink-headings](https://github.com/remarkjs/remark-autolink-headings/blob/master/package.json), so maybe that’s a good reference?

**Comment by wooorm** [comment]
I’m closing the issues here and archiving the repo. It isn’t really maintained, was never finished (it’s not a task very suitable to syntax trees, but could work in a compiler/generator/stringifier). [Prettier](https://github.com/prettier/prettier) is the better option.
